import { ref } from "vue";

export function useMockTables() {
  const courses = ref([
    {
      id: 1,
      name: "Administração",
      university: "Faculdade de Ciências e Engenharia",
      campus: "Tupã",
      type: "Bacharelado",
      studyPeriod: "Integral",
      dropoutRate: 13,
      students: [
        {
          name: "Felipe Zangarini da Silva",
          NC: "Administração",
          P: "N",
          R: "B",
          G: "M",
          EM: "PB",
          C: "EP",
          TI: "V",
          S: "CO",
          AM: 2018,
          IM: 19,
          NAVG: 7.5,
          NMAX: 9.2,
          NMIN: 5.8,
          NMED: 7.6,
          FMAX: 100,
          FMIN: 75,
          FAVG: 88,
          FMED: 89,
          PR: 10,
          PE: 5,
          QD: 48,
          AN: 1999,
          RE: "12%",
          impact: {
            NC: "1%", P: "1%", R: "1%", G: "1%", EM: "6%", C: "6%", TI: "5%", S: "20%",
            AM: "4%", IM: "3%", NAVG: "14%", NMAX: "3%", NMIN: "3%", NMED: "3%",
            FMAX: "2%", FMIN: "2%", FAVG: "11%", FMED: "2%", PR: "7%", PE: "2%",
            QD: "2%", AN: "1%"
          },
        },
        {
          name: "Alessandra Regina Silva de Paula",
          NC: "Administração",
          P: "N",
          R: "P",
          G: "F",
          EM: "PR",
          C: "SU",
          TI: "V",
          S: "CO",
          AM: 2019,
          IM: 18,
          NAVG: 8.1,
          NMAX: 9.8,
          NMIN: 6.2,
          NMED: 8.0,
          FMAX: 100,
          FMIN: 80,
          FAVG: 93,
          FMED: 92,
          PR: 5,
          PE: 2,
          QD: 50,
          AN: 2001,
          RE: "8%",
          impact: {
            NC: "1%", P: "1%", R: "1%", G: "1%", EM: "6%", C: "6%", TI: "5%", S: "20%",
            AM: "4%", IM: "3%", NAVG: "14%", NMAX: "3%", NMIN: "3%", NMED: "3%",
            FMAX: "2%", FMIN: "2%", FAVG: "11%", FMED: "2%", PR: "7%", PE: "2%",
            QD: "2%", AN: "1%"
          },
        },
        {
          name: "João Victor Ribeiro",
          NC: "Administração",
          P: "N",
          R: "B",
          G: "M",
          EM: "PB",
          C: "EP",
          TI: "TE",
          S: "CA",
          AM: 2020,
          IM: 21,
          NAVG: 5.9,
          NMAX: 8.3,
          NMIN: 4.2,
          NMED: 6.0,
          FMAX: 95,
          FMIN: 60,
          FAVG: 72,
          FMED: 74,
          PR: 25,
          PE: 12,
          QD: 42,
          AN: 1999,
          RE: "63%",
          impact: {
            NC: "1%", P: "1%", R: "1%", G: "1%", EM: "6%", C: "6%", TI: "5%", S: "20%",
            AM: "4%", IM: "3%", NAVG: "14%", NMAX: "3%", NMIN: "3%", NMED: "3%",
            FMAX: "2%", FMIN: "2%", FAVG: "11%", FMED: "2%", PR: "7%", PE: "2%",
            QD: "2%", AN: "1%"
          },
        },
      ],
    },
    {
      id: 2,
      name: "Bacharel em Ciências da Computação",
      university: "Faculdade de Ciências e Tecnologia",
      campus: "Presidente Prudente",
      type: "Bacharelado",
      studyPeriod: "Vespertino",
      dropoutRate: 20,
      students: [
        {
          name: "Lucas Andrade Monteiro",
          NC: "Ciências da Computação",
          P: "V",
          R: "B",
          G: "M",
          EM: "PB",
          C: "EP",
          TI: "V",
          S: "CO",
          AM: 2019,
          IM: 18,
          NAVG: 8.4,
          NMAX: 9.7,
          NMIN: 7.0,
          NMED: 8.5,
          FMAX: 100,
          FMIN: 82,
          FAVG: 95,
          FMED: 94,
          PR: 4,
          PE: 1,
          QD: 52,
          AN: 2001,
          RE: 6,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Gabriela Nunes Ferreira",
          NC: "Ciências da Computação",
          P: "V",
          R: "P",
          G: "F",
          EM: "PR",
          C: "SU",
          TI: "V",
          S: "CO",
          AM: 2020,
          IM: 19,
          NAVG: 7.8,
          NMAX: 9.1,
          NMIN: 6.5,
          NMED: 7.9,
          FMAX: 100,
          FMIN: 78,
          FAVG: 90,
          FMED: 91,
          PR: 7,
          PE: 3,
          QD: 46,
          AN: 2001,
          RE: 15,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Rafael Cardoso Pinto",
          NC: "Ciências da Computação",
          P: "V",
          R: "B",
          G: "M",
          EM: "PB",
          C: "EP",
          TI: "V",
          S: "CA",
          AM: 2021,
          IM: 22,
          NAVG: 5.1,
          NMAX: 8.5,
          NMIN: 3.0,
          NMED: 5.2,
          FMAX: 96,
          FMIN: 50,
          FAVG: 70,
          FMED: 68,
          PR: 35,
          PE: 20,
          QD: 38,
          AN: 1999,
          RE: 78,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
      ],
    },
    {
      id: 3,
      name: "Física",
      university: "Faculdade de Ciências",
      campus: "Bauru",
      type: "Licenciatura",
      studyPeriod: "Noturno",
      dropoutRate: 85,
      students: [
        {
          name: "Rodrigo Alves Lima",
          NC: "Física",
          P: "N",
          R: "B",
          G: "M",
          EM: "PB",
          C: "EP",
          TI: "V",
          S: "CA",
          AM: 2019,
          IM: 20,
          NAVG: 4.5,
          NMAX: 7.8,
          NMIN: 2.0,
          NMED: 4.2,
          FMAX: 90,
          FMIN: 40,
          FAVG: 55,
          FMED: 52,
          PR: 45,
          PE: 30,
          QD: 40,
          AN: 1999,
          RE: 88,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Ana Paula Souza",
          NC: "Física",
          P: "N",
          R: "P",
          G: "F",
          EM: "PR",
          C: "SU",
          TI: "V",
          S: "CO",
          AM: 2018,
          IM: 19,
          NAVG: 6.8,
          NMAX: 8.5,
          NMIN: 4.2,
          NMED: 6.5,
          FMAX: 97,
          FMIN: 60,
          FAVG: 82,
          FMED: 80,
          PR: 20,
          PE: 10,
          QD: 46,
          AN: 1999,
          RE: 25,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Pedro Henrique Ramos",
          NC: "Física",
          P: "N",
          R: "B",
          G: "M",
          EM: "PB",
          C: "EP",
          TI: "Transferência_Interna",
          S: "CA",
          AM: 2020,
          IM: 21,
          NAVG: 3.8,
          NMAX: 6.5,
          NMIN: 1.5,
          NMED: 4.0,
          FMAX: 85,
          FMIN: 35,
          FAVG: 50,
          FMED: 47,
          PR: 55,
          PE: 25,
          QD: 38,
          AN: 1999,
          RE: 91,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
      ],
    },
    {
      id: 4,
      name: "Ciências Biológicas",
      university: "Instituto de Biociências",
      campus: "Rio Claro",
      type: "Licenciatura",
      studyPeriod: "Integral",
      dropoutRate: 30,
      students: [
        {
          name: "Isabela Monteiro Souza",
          NC: "Ciências Biológicas",
          P: "I",
          R: "P",
          G: "F",
          EM: "PR",
          C: "SU",
          TI: "V",
          S: "CO",
          AM: 2018,
          IM: 18,
          NAVG: 8.3,
          NMAX: 9.5,
          NMIN: 7.2,
          NMED: 8.2,
          FMAX: 100,
          FMIN: 85,
          FAVG: 94,
          FMED: 93,
          PR: 5,
          PE: 2,
          QD: 48,
          AN: 2000,
          RE: 10,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Renato Lima Oliveira",
          NC: "Ciências Biológicas",
          P: "I",
          R: "B",
          G: "M",
          EM: "PB",
          C: "EP",
          TI: "V",
          S: "CO",
          AM: 2019,
          IM: 19,
          NAVG: 7.5,
          NMAX: 9.0,
          NMIN: 5.5,
          NMED: 7.6,
          FMAX: 100,
          FMIN: 78,
          FAVG: 88,
          FMED: 89,
          PR: 12,
          PE: 6,
          QD: 45,
          AN: 2000,
          RE: 18,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Camila Duarte Nascimento",
          NC: "Ciências Biológicas",
          P: "I",
          R: "P",
          G: "F",
          EM: "PB",
          C: "EP",
          TI: "Transferência_Externa",
          S: "CA",
          AM: 2020,
          IM: 22,
          NAVG: 6.1,
          NMAX: 8.0,
          NMIN: 3.8,
          NMED: 6.0,
          FMAX: 96,
          FMIN: 55,
          FAVG: 70,
          FMED: 72,
          PR: 25,
          PE: 12,
          QD: 41,
          AN: 1998,
          RE: 58,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
      ],
    },
    {
      id: 5,
      name: "Engenharia Aeronáutica",
      university: "Câmpus Experimental de São João da Boa Vista",
      campus: "São João da Boa Vista",
      type: "Bacharelado",
      studyPeriod: "Integral",
      dropoutRate: 67,
      students: [
        {
          name: "Carlos Henrique Borges",
          NC: "Engenharia Aeronáutica",
          P: "I",
          R: "B",
          G: "M",
          EM: "PR",
          C: "SU",
          TI: "V",
          S: "CO",
          AM: 2018,
          IM: 18,
          NAVG: 7.0,
          NMAX: 9.0,
          NMIN: 4.8,
          NMED: 6.9,
          FMAX: 98,
          FMIN: 65,
          FAVG: 85,
          FMED: 84,
          PR: 20,
          PE: 10,
          QD: 50,
          AN: 2000,
          RE: 25,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Larissa Souza Teixeira",
          NC: "Engenharia Aeronáutica",
          P: "I",
          R: "P",
          G: "F",
          EM: "PB",
          C: "EP",
          TI: "V",
          S: "CA",
          AM: 2020,
          IM: 21,
          NAVG: 5.5,
          NMAX: 8.0,
          NMIN: 3.0,
          NMED: 5.2,
          FMAX: 95,
          FMIN: 50,
          FAVG: 68,
          FMED: 70,
          PR: 30,
          PE: 20,
          QD: 42,
          AN: 1999,
          RE: 70,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Matheus Oliveira Campos",
          NC: "Engenharia Aeronáutica",
          P: "I",
          R: "B",
          G: "M",
          EM: "PR",
          C: "SU",
          TI: "Transferência_Interna",
          S: "CA",
          AM: 2019,
          IM: 19,
          NAVG: 6.0,
          NMAX: 8.2,
          NMIN: 3.5,
          NMED: 5.8,
          FMAX: 90,
          FMIN: 55,
          FAVG: 73,
          FMED: 75,
          PR: 28,
          PE: 15,
          QD: 45,
          AN: 2000,
          RE: 62,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
      ],
    },
    {
      id: 6,
      name: "Licenciatura em Matemática",
      university: "Faculdade de Ciências e Tecnologia",
      campus: "Presidente Prudente",
      type: "Licenciatura",
      studyPeriod: "Noturno",
      dropoutRate: 89,
      students: [
        {
          name: "André Luiz Cardoso",
          NC: "Matemática",
          P: "N",
          R: "B",
          G: "M",
          EM: "PB",
          C: "EP",
          TI: "V",
          S: "CA",
          AM: 2019,
          IM: 20,
          NAVG: 4.2,
          NMAX: 7.0,
          NMIN: 2.0,
          NMED: 4.0,
          FMAX: 85,
          FMIN: 35,
          FAVG: 55,
          FMED: 50,
          PR: 50,
          PE: 30,
          QD: 40,
          AN: 1999,
          RE: 90,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Juliana Mendes Carvalho",
          NC: "Matemática",
          P: "N",
          R: "P",
          G: "F",
          EM: "PR",
          C: "SU",
          TI: "V",
          S: "CO",
          AM: 2018,
          IM: 19,
          NAVG: 6.9,
          NMAX: 8.5,
          NMIN: 4.3,
          NMED: 6.8,
          FMAX: 95,
          FMIN: 60,
          FAVG: 80,
          FMED: 82,
          PR: 22,
          PE: 12,
          QD: 44,
          AN: 1999,
          RE: 35,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Carlos Eduardo Ribeiro",
          NC: "Matemática",
          P: "N",
          R: "B",
          G: "M",
          EM: "PB",
          C: "EP",
          TI: "Transferência_Externa",
          S: "CA",
          AM: 2020,
          IM: 22,
          NAVG: 3.5,
          NMAX: 6.8,
          NMIN: 1.0,
          NMED: 3.8,
          FMAX: 80,
          FMIN: 30,
          FAVG: 48,
          FMED: 45,
          PR: 60,
          PE: 35,
          QD: 38,
          AN: 1998,
          RE: 92,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
      ],
    },
    {
      id: 7,
      name: "Pedagogia",
      university: "Faculdade de Ciências e Letras",
      campus: "Araraquara",
      type: "Licenciatura",
      studyPeriod: "Noturno",
      dropoutRate: 12,
      students: [
        {
          name: "Beatriz Oliveira Santos",
          NC: "Pedagogia",
          P: "N",
          R: "P",
          G: "F",
          EM: "PR",
          C: "SU",
          TI: "V",
          S: "CO",
          AM: 2018,
          IM: 18,
          NAVG: 8.6,
          NMAX: 9.5,
          NMIN: 7.2,
          NMED: 8.4,
          FMAX: 100,
          FMIN: 90,
          FAVG: 96,
          FMED: 95,
          PR: 4,
          PE: 2,
          QD: 48,
          AN: 2000,
          RE: 6,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Patrícia Lima Nogueira",
          NC: "Pedagogia",
          P: "N",
          R: "P",
          G: "F",
          EM: "PB",
          C: "EP",
          TI: "V",
          S: "CO",
          AM: 2019,
          IM: 19,
          NAVG: 8.1,
          NMAX: 9.2,
          NMIN: 6.8,
          NMED: 8.0,
          FMAX: 99,
          FMIN: 85,
          FAVG: 92,
          FMED: 91,
          PR: 6,
          PE: 3,
          QD: 47,
          AN: 2001,
          RE: 9,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
        {
          name: "Rodrigo Martins Pereira",
          NC: "Pedagogia",
          P: "N",
          R: "B",
          G: "M",
          EM: "PB",
          C: "EP",
          TI: "Transferência_Externa",
          S: "CA",
          AM: 2020,
          IM: 22,
          NAVG: 5.7,
          NMAX: 8.0,
          NMIN: 3.2,
          NMED: 5.8,
          FMAX: 92,
          FMIN: 55,
          FAVG: 71,
          FMED: 70,
          PR: 28,
          PE: 15,
          QD: 40,
          AN: 1998,
          RE: 55,
          impact: {
            NC: 1, P: 1, R: 1, G: 1, EM: 6, C: 6, TI: 5, S: 20,
            AM: 4, IM: 3, NAVG: 14, NMAX: 3, NMIN: 3, NMED: 3,
            FMAX: 2, FMIN: 2, FAVG: 11, FMED: 2, PR: 7, PE: 2,
            QD: 2, AN: 1
          },
        },
      ],
    }
  ]);

  return { courses };
}
